// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pb/transport.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	FrameType_FRAME_TYPE_DATA        FrameType = 1
	FrameType_FRAME_TYPE_PING        FrameType = 2
	FrameType_FRAME_TYPE_PONG        FrameType = 3
	FrameType_FRAME_TYPE_HANDSHAKE   FrameType = 4
	FrameType_FRAME_TYPE_CLOSE       FrameType = 5
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_UNSPECIFIED",
		1: "FRAME_TYPE_DATA",
		2: "FRAME_TYPE_PING",
		3: "FRAME_TYPE_PONG",
		4: "FRAME_TYPE_HANDSHAKE",
		5: "FRAME_TYPE_CLOSE",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"FRAME_TYPE_DATA":        1,
		"FRAME_TYPE_PING":        2,
		"FRAME_TYPE_PONG":        3,
		"FRAME_TYPE_HANDSHAKE":   4,
		"FRAME_TYPE_CLOSE":       5,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_transport_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_pb_transport_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_pb_transport_proto_rawDescGZIP(), []int{0}
}

// Frame represents a single transport frame.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameId       uint64                 `protobuf:"varint,1,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Type          FrameType              `protobuf:"varint,3,opt,name=type,proto3,enum=aether.grpc.v1.FrameType" json:"type,omitempty"`
	AckedFrames   []uint64               `protobuf:"varint,4,rep,packed,name=acked_frames,json=ackedFrames,proto3" json:"acked_frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_pb_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pb_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pb_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetFrameId() uint64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *Frame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Frame) GetType() FrameType {
	if x != nil {
		return x.Type
	}
	return FrameType_FRAME_TYPE_UNSPECIFIED
}

func (x *Frame) GetAckedFrames() []uint64 {
	if x != nil {
		return x.AckedFrames
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pb_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pb_transport_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *PingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PingResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestampNs int64                  `protobuf:"varint,1,opt,name=client_timestamp_ns,json=clientTimestampNs,proto3" json:"client_timestamp_ns,omitempty"`
	ServerTimestampNs int64                  `protobuf:"varint,2,opt,name=server_timestamp_ns,json=serverTimestampNs,proto3" json:"server_timestamp_ns,omitempty"`
	NodeId            string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_pb_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_pb_transport_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetClientTimestampNs() int64 {
	if x != nil {
		return x.ClientTimestampNs
	}
	return 0
}

func (x *PingResponse) GetServerTimestampNs() int64 {
	if x != nil {
		return x.ServerTimestampNs
	}
	return 0
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Challenge     []byte                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Version       uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_pb_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_pb_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_pb_transport_proto_rawDescGZIP(), []int{3}
}

func (x *Handshake) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Handshake) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Handshake) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *Handshake) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_pb_transport_proto protoreflect.FileDescriptor

const file_pb_transport_proto_rawDesc = "" +
	"\n" +
	"\x12pb/transport.proto\x12\x0eaether.grpc.v1\"\x88\x01\n" +
	"\x05Frame\x12\x19\n" +
	"\bframe_id\x18\x01 \x01(\x04R\aframeId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.aether.grpc.v1.FrameTypeR\x04type\x12!\n" +
	"\facked_frames\x18\x04 \x03(\x04R\vackedFrames\"I\n" +
	"\vPingRequest\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\x87\x01\n" +
	"\fPingResponse\x12.\n" +
	"\x13client_timestamp_ns\x18\x01 \x01(\x03R\x11clientTimestampNs\x12.\n" +
	"\x13server_timestamp_ns\x18\x02 \x01(\x03R\x11serverTimestampNs\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"\x80\x01\n" +
	"\tHandshake\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\fR\tchallenge\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion*\x96\x01\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFRAME_TYPE_DATA\x10\x01\x12\x13\n" +
	"\x0fFRAME_TYPE_PING\x10\x02\x12\x13\n" +
	"\x0fFRAME_TYPE_PONG\x10\x03\x12\x18\n" +
	"\x14FRAME_TYPE_HANDSHAKE\x10\x04\x12\x14\n" +
	"\x10FRAME_TYPE_CLOSE\x10\x052\x91\x01\n" +
	"\x10TransportService\x12:\n" +
	"\x06Stream\x12\x15.aether.grpc.v1.Frame\x1a\x15.aether.grpc.v1.Frame(\x010\x01\x12A\n" +
	"\x04Ping\x12\x1b.aether.grpc.v1.PingRequest\x1a\x1c.aether.grpc.v1.PingResponseB!Z\x1fgithub.com/ORBTR/aether/grpc/pbb\x06proto3"

var (
	file_pb_transport_proto_rawDescOnce sync.Once
	file_pb_transport_proto_rawDescData []byte
)

func file_pb_transport_proto_rawDescGZIP() []byte {
	file_pb_transport_proto_rawDescOnce.Do(func() {
		file_pb_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_transport_proto_rawDesc), len(file_pb_transport_proto_rawDesc)))
	})
	return file_pb_transport_proto_rawDescData
}

var file_pb_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_transport_proto_goTypes = []any{
	(FrameType)(0),       // 0: aether.grpc.v1.FrameType
	(*Frame)(nil),        // 1: aether.grpc.v1.Frame
	(*PingRequest)(nil),  // 2: aether.grpc.v1.PingRequest
	(*PingResponse)(nil), // 3: aether.grpc.v1.PingResponse
	(*Handshake)(nil),    // 4: aether.grpc.v1.Handshake
}
var file_pb_transport_proto_depIdxs = []int32{
	0, // 0: aether.grpc.v1.Frame.type:type_name -> aether.grpc.v1.FrameType
	1, // 1: aether.grpc.v1.TransportService.Stream:input_type -> aether.grpc.v1.Frame
	2, // 2: aether.grpc.v1.TransportService.Ping:input_type -> aether.grpc.v1.PingRequest
	1, // 3: aether.grpc.v1.TransportService.Stream:output_type -> aether.grpc.v1.Frame
	3, // 4: aether.grpc.v1.TransportService.Ping:output_type -> aether.grpc.v1.PingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_transport_proto_init() }
func file_pb_transport_proto_init() {
	if File_pb_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_transport_proto_rawDesc), len(file_pb_transport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_transport_proto_goTypes,
		DependencyIndexes: file_pb_transport_proto_depIdxs,
		EnumInfos:         file_pb_transport_proto_enumTypes,
		MessageInfos:      file_pb_transport_proto_msgTypes,
	}.Build()
	File_pb_transport_proto = out.File
	file_pb_transport_proto_goTypes = nil
	file_pb_transport_proto_depIdxs = nil
}
