// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: rpc/pb/rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RPCRequest represents a direct RPC call over the mesh network.
type RPCRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Handler   string                 `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	Payload   []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Context   map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutNs int64                  `protobuf:"varint,5,opt,name=timeout_ns,json=timeoutNs,proto3" json:"timeout_ns,omitempty"` // nanoseconds (Duration)
	SessionId string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TraceId   string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Hops      int32                  `protobuf:"varint,8,opt,name=hops,proto3" json:"hops,omitempty"` // forwarding hop counter, max 6
	// Intelligent routing fields
	TargetNodeId  string   `protobuf:"bytes,9,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"` // ultimate destination node
	RouteList     []string `protobuf:"bytes,10,rep,name=route_list,json=routeList,proto3" json:"route_list,omitempty"`           // ordered remaining hops [next, ..., target]
	RequestNonce  string   `protobuf:"bytes,11,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`  // unique per parallel probe (dedup key)
	Deadline      int64    `protobuf:"varint,12,opt,name=deadline,proto3" json:"deadline,omitempty"`                             // absolute deadline (unix nanos)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCRequest) Reset() {
	*x = RPCRequest{}
	mi := &file_rpc_pb_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCRequest) ProtoMessage() {}

func (x *RPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCRequest.ProtoReflect.Descriptor instead.
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RPCRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RPCRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *RPCRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RPCRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RPCRequest) GetTimeoutNs() int64 {
	if x != nil {
		return x.TimeoutNs
	}
	return 0
}

func (x *RPCRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RPCRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RPCRequest) GetHops() int32 {
	if x != nil {
		return x.Hops
	}
	return 0
}

func (x *RPCRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *RPCRequest) GetRouteList() []string {
	if x != nil {
		return x.RouteList
	}
	return nil
}

func (x *RPCRequest) GetRequestNonce() string {
	if x != nil {
		return x.RequestNonce
	}
	return ""
}

func (x *RPCRequest) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

// RPCResponse represents the result of an RPC call.
type RPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	LatencyNs     int64                  `protobuf:"varint,5,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"` // nanoseconds (Duration)
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	mi := &file_rpc_pb_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_pb_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_rpc_pb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RPCResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RPCResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RPCResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RPCResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RPCResponse) GetLatencyNs() int64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

func (x *RPCResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_rpc_pb_rpc_proto protoreflect.FileDescriptor

const file_rpc_pb_rpc_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/pb/rpc.proto\x12\raether.rpc.v1\"\xc1\x03\n" +
	"\n" +
	"RPCRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12@\n" +
	"\acontext\x18\x04 \x03(\v2&.aether.rpc.v1.RPCRequest.ContextEntryR\acontext\x12\x1d\n" +
	"\n" +
	"timeout_ns\x18\x05 \x01(\x03R\ttimeoutNs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x12\n" +
	"\x04hops\x18\b \x01(\x05R\x04hops\x12$\n" +
	"\x0etarget_node_id\x18\t \x01(\tR\ftargetNodeId\x12\x1d\n" +
	"\n" +
	"route_list\x18\n" +
	" \x03(\tR\trouteList\x12#\n" +
	"\rrequest_nonce\x18\v \x01(\tR\frequestNonce\x12\x1a\n" +
	"\bdeadline\x18\f \x01(\x03R\bdeadline\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x02\n" +
	"\vRPCResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\x05 \x01(\x03R\tlatencyNs\x12D\n" +
	"\bmetadata\x18\x06 \x03(\v2(.aether.rpc.v1.RPCResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B Z\x1egithub.com/ORBTR/aether/rpc/pbb\x06proto3"

var (
	file_rpc_pb_rpc_proto_rawDescOnce sync.Once
	file_rpc_pb_rpc_proto_rawDescData []byte
)

func file_rpc_pb_rpc_proto_rawDescGZIP() []byte {
	file_rpc_pb_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_pb_rpc_proto_rawDesc), len(file_rpc_pb_rpc_proto_rawDesc)))
	})
	return file_rpc_pb_rpc_proto_rawDescData
}

var file_rpc_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_pb_rpc_proto_goTypes = []any{
	(*RPCRequest)(nil),  // 0: aether.rpc.v1.RPCRequest
	(*RPCResponse)(nil), // 1: aether.rpc.v1.RPCResponse
	nil,                 // 2: aether.rpc.v1.RPCRequest.ContextEntry
	nil,                 // 3: aether.rpc.v1.RPCResponse.MetadataEntry
}
var file_rpc_pb_rpc_proto_depIdxs = []int32{
	2, // 0: aether.rpc.v1.RPCRequest.context:type_name -> aether.rpc.v1.RPCRequest.ContextEntry
	3, // 1: aether.rpc.v1.RPCResponse.metadata:type_name -> aether.rpc.v1.RPCResponse.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_pb_rpc_proto_init() }
func file_rpc_pb_rpc_proto_init() {
	if File_rpc_pb_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_pb_rpc_proto_rawDesc), len(file_rpc_pb_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_pb_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_pb_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_pb_rpc_proto_msgTypes,
	}.Build()
	File_rpc_pb_rpc_proto = out.File
	file_rpc_pb_rpc_proto_goTypes = nil
	file_rpc_pb_rpc_proto_depIdxs = nil
}
